services:
    db:
        image: postgres:16
        container_name: poe-tracker-postgres

        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}

        volumes:
           - postgres_data:/var/lib/postgresql/data

        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U gears -d poe_tracker_db"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

    pgadmin:
        image: dpage/pgadmin4:9.15

        profiles:
            - tools

        environment: 
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

        ports:
            - "127.0.0.1:5050:80"
        
        depends_on:
            db:
                condition: service_healthy

    fetcher:
        build: .
        container_name: poe-tracker-fetcher

        depends_on:
            db:
                condition: service_healthy

        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            POE_LEAGUE: ${POE_LEAGUE}

        restart: unless-stopped

    grafana:
        image: grafana/grafana:13.0.1-security-01
        container_name: poe-tracker-grafana

        ports:
            - "4000:3000"

        environment:
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}

        volumes:
            - grafana-data:/var/lib/grafana
            - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
            - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
            - ./grafana/dashboards:/var/lib/grafana/dashboards:ro

        depends_on:
            db:
                condition: service_healthy
        

volumes:
    postgres_data:
    grafana-data: