services:
    db:
        image: postgres:latest
        container_name: poe-tracker-postgres
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: poe_tracker_db
        ports:
            - "5432:5432"
        volumes:
           - poe_tracker_postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U gears -d poe_tracker_db"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

    pgadmin:
        image: dpage/pgadmin4
        environment: 
            PGADMIN_DEFAULT_EMAIL: admin@gmail.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        depends_on:
            - db

    fetcher:
        build: .
        container_name: poe-tracker-fetcher
        depends_on:
            db:
                condition: service_healthy
        environment:
            DB_HOST: db
            DB_PORT: 5432
            DB_NAME: poe_tracker_db
            DB_USER: admin
            DB_PASSWORD: admin
            POE_LEAGUE: Fate+of+the+Vaal
        restart: unless-stopped

    grafana:
        image: grafana/grafana:latest
        container_name: poe-tracker-grafana
        ports:
            - "3000:3000"
        volumes:
            - poe-tracker-grafana-data:/var/lib/grafana
        depends_on:
            db:
                condition: service_healthy
volumes:
    poe_tracker_postgres_data:
    poe-tracker-grafana-data: